runtime: python37
entrypoint: gunicorn -b :$PORT run:app
inbound_services:
- warmup
automatic_scaling:
  target_cpu_utilization: 0.25
  min_instances: 1
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
